#!/usr/bin/env bash
set -e

# Build the release version
echo "Building project in release mode..."
cargo build --release

# Path to binaries
SCRAPER="./target/release/paul-scrape-rs"
CONVERTER="./target/release/convertjson"
BASE_URL="https://paul.uni-paderborn.de/"

# Get the newest semester
echo "Fetching available semesters..."
# We use the scraper to list semesters. The output is sorted by date descending (newest first).
SEMESTER=$($SCRAPER --list-semesters | head -n 1)

if [ -z "$SEMESTER" ]; then
    echo "Error: Could not retrieve semesters."
    exit 1
fi

# Check for upload flag
UPLOAD=false
if [ "$1" == "--upload" ]; then
    UPLOAD=true
fi

echo "Selected semester: '$SEMESTER'"

# Run scraping
# Note: The scraper takes two positional arguments: <BASE_URL> <SEMESTER>
echo "Starting scrape for '$SEMESTER'..."
$SCRAPER "$BASE_URL" "$SEMESTER"

# Run conversion
# This reads state.json (generated by scraper) and writes semester.json
echo "Converting state.json to semester.json..."
$CONVERTER

echo "Done! Output saved to semester.json"

if [ "$UPLOAD" = true ]; then
    if [ ! -f .api_key ]; then
        echo "Error: .api_key file not found. Cannot upload."
        exit 1
    fi
    API_KEY=$(cat .api_key)
    echo "Uploading to Pauline..."
    curl -X POST --data-binary @- "https://pauline-upb.de/api/v1/admin/semester" \
        -H "API-Key: $API_KEY" \
        -H "Content-Type: application/json" < ./semester.json
else
    echo "Dry run finished. Use --upload to upload semester.json to Pauline."
fi
