"""search index

Revision ID: 278aca658ba6
Revises: 1ce4e17617c1
Create Date: 2022-01-12 10:41:34.182181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278aca658ba6'
down_revision = '1ce4e17617c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
