"""semester created timestamp

Revision ID: 50a8e19d9668
Revises: bed1aefe514f
Create Date: 2022-03-10 19:01:45.914837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a8e19d9668'
down_revision = 'bed1aefe514f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semester', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semester', 'created')
    # ### end Alembic commands ###
