"""larger varchars

Revision ID: 674b920b5a4d
Revises: b243b7ad60ad
Create Date: 2022-07-08 23:30:49.154090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674b920b5a4d'
down_revision = 'b243b7ad60ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'room',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.VARCHAR(length=265),
               existing_nullable=False)
    op.alter_column('appointment', 'instructors',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.alter_column('course', 'name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.alter_column('course', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('course', 'instructors',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('small_group', 'name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('small_group', 'name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('course', 'instructors',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('course', 'description',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('course', 'name',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('appointment', 'instructors',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('appointment', 'room',
               existing_type=sa.VARCHAR(length=265),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###
