"""course intructors and ou

Revision ID: b243b7ad60ad
Revises: 50a8e19d9668
Create Date: 2022-03-19 12:11:36.380940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b243b7ad60ad'
down_revision = '50a8e19d9668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('instructors', sa.VARCHAR(length=256), nullable=True))
    op.add_column('course', sa.Column('ou', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'ou')
    op.drop_column('course', 'instructors')
    # ### end Alembic commands ###
