"""overflow fix

Revision ID: bed1aefe514f
Revises: 278aca658ba6
Create Date: 2022-01-26 11:52:48.248018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed1aefe514f'
down_revision = '278aca658ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'room',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('appointment', 'instructors',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('course', 'name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.alter_column('small_group', 'name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('small_group', 'name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('course', 'name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('appointment', 'instructors',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('appointment', 'room',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
